---
- hosts: geo
  vars:
    mvtraits_dir: "{{ install_basepath }}/mvtraits"
    analysis_dir: "{{ install_basepath }}/np-traits-analysis"
    local_data_dir: "/home/ashiklom/Projects/new-phytologist-traits/preprocess-try"
    data_dir: "{{ analysis_dir }}/extdata"
  tasks:
    - include_tasks: setup.yml
    - include_tasks: session_info.yml
    - include_tasks: try_data.yml
