---
title: "Does the leaf economic spectrum hold within plant functional types? A Bayesian hierarchical meta-analysis"
author:
  - >
    Alexey N. Shiklomanov$^1$
    Elizabeth M. Cowdery$^1$,
    Michael Bahn$^2$,
    Chaeho Byun$^3$,
    Joseph Craine$^4$,
    Andrés Gonzalez-Melo$^5$,
    Steven Jansen$^6$,
    Nathan Kraft$^7$,
    Koen Kramer$^{8}$,
    Vanessa Minden$^{9,10}$,
    Ülo Niinemets$^{11}$,
    Yusuke Onoda$^{12}$,
    Enio Egon Sosinski$^{13}$,
    Nadejda A. Soudzilovskaia$^{14}$,
    Michael C. Dietze$^1$
bibliography:
  - library.bib
  - extra.bib
  - tryrefs.bib
csl: new-phytologist.csl
output:
  bookdown::word_document2:
    toc: no
    reference_docx: ~/Projects/misc/pandoc-docx-template/custom.docx
  bookdown::pdf_document2:
    latex_engine: xelatex
    toc: no
    includes:
      in_header: preamble.tex
---
<div custom-style="Affiliation">
$^1$Department of Earth & Environment, Boston University, Boston, MA 02215, USA;
$^2$Institute of Ecology, University of Innsbruck, 6020 Innsbruck, Austria;
$^3$School of Biological Sciences, Seoul National University, Gwanak-ro 1, 08826, Seoul, Seoul, South Korea;
$^4$Jonah Ventures, Manhattan, KS 66502, USA;
$^5$Universidad del Rosario. Facultad de Ciencias Naturales y Matemáticas. Carrera 26 #63B-48. Bogotá, Colombia;
$^6$Institute of Systematic Botany and Ecology, Ulm University, Ulm, Germany;
$^7$Department of Ecology and Evolutionary Biology, University of California Los Angeles, Los Angeles, CA 90095, USA;
$^{8}$Vegetation, Forest, and Landscape Ecology, Wageningen Environmental Research and Wageningen University, Wageningen, Gelderland, The Netherlands;
$^{9}$Institute for Biology and Environmental Sciences, Carl von Ossietzky-University of Oldenburg, Carl von Ossietzky Str. 9-11, 26129 Oldenburg, Germany;
$^{10}$Department of Biology, Ecology and Evolution, Vrije Universiteit Brussel, Pleinlaan 2, 1050 Brussels;
$^{11}$Institute of Agricultural and Environmental Sciences, Estonian University of Life Sciences, Kreutzwaldi 1, 51014 Tartu, Estonia;
$^{12}$Graduate School of Agriculture, Kyoto University, Kyoto, 606-8502, Japan;
$^{13}$Embrapa Temperate Agriculture, Rodovia BR 392, Km 78, CEP 96010-971 Pelotas, RS, Brazil;
$^{14}$Conservation Biology Department, Institute of Environmental Sciences, Leiden University, Leiden, The Netherlands
</div>

<div custom-style="Single space">
Corresponding author:

Alexey Shiklomanov,

telephone: +1 (302) 897-3348,

email: ashiklom\@bu.edu

Key words: Functional trade-off; hierarchical modeling; trait variation; ecological modeling; leaf morphology; leaf biochemistry
</div>

```{r wordcount, echo = FALSE}
fnames <- c(
  introduction = "01_introduction.md",
  methods = "02_methods.Rmd",
  results = "03_results.Rmd",
  discussion = "04_discussion.md"
)
files <- here::here(
  "manuscript", 
  fnames
)
names(files) <- names(fnames)

getwc <- function(f) {
  ct <- withr::with_options(
    list(knitr.table.format = "pandoc"),
    wordcountaddin::text_stats(f)
  )
  wline <- ct[3]
  wlist <- strsplit(wline, split = "[[:space:]]+")
  as.numeric(wlist[[1]][3])
}

wc_table <- data.frame(wordcount = vapply(files, getwc, numeric(1)))
wc_total <- rbind(wc_table, sum(wc_table$wordcount))
wc_total$percent <- 100 * wc_total$wordcount / 
  sum(wc_total$wordcount[-nrow(wc_total)])
rownames(wc_total)[nrow(wc_total)] <- "total"
knitr::kable(wc_total, digits = 1)
```

<div custom-style="Heading, no number">Summary</div>

* We investigated whether global leaf economic relationships across plant functional types (PFTs) are also present within-PFTs, and the extent to which this hierarchical structure can be used to constrain trait estimates.

* We developed a hierarchical multivariate Bayesian model that assumes separate means and covariance structures within and across PFTs and fit this model to seven leaf traits from the TRY database: longevity, specific leaf area, nitrogen content, phosphorus content, dark respiration rate, maximum photosynthetic carboxylation rate ($V_{c,max}$), and maximum photosynthetic electron transport rate ($J_{max}$). 
We evaluated the ability of this model to estimate trait means and reproduce leaf economic trade-offs.

* Trait correlations were generally consistent in direction within and across PFTs, and consistent with predictions of the leaf economic spectrum.
However, correlation strength varied substantially across PFTs indicating that leaf economic relationships within PFTs are often confounded by the unique physiology of certain plant types or environmental conditions in certain biomes.

* Leveraging covariance in multivariate models reduced uncertainties in mean trait estimates, particularly for undersampled trait-PFT combinations.
However, additional constraint from the across-PFT hierarchy was limited compared to the simple multivariate models.
